### ISSUE TITLE
Crashes after SublimeLinter4 upgrade

### ISSUE THREAD

**Issue by kgizdov** [SublimeLinter/SublimeLinter-cppcheck#13]
After the recent upgrade to SublimeLinter 4, SublimeLinter-cppcheck crashes with following error:
```shell
SublimeLinter: ERROR: Linter crashed.

Traceback (most recent call last):
  File "lint.backend in /home/gizdov/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 97, in execute_lint_task
  File "lint.linter in /home/gizdov/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 813, in lint
  File "lint.linter in /home/gizdov/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 847, in find_errors
  File "linter in /home/gizdov/.config/sublime-text-3/Installed Packages/SublimeLinter-cppcheck.sublime-package", line 50, in split_match
  File "lint.linter in /home/gizdov/.config/sublime-text-3/Installed Packages/SublimeLinter.sublime-package", line 865, in split_match
AttributeError: 'NoneType' object has no attribute 'groupdict'
ERROR:SublimeLinter.lint.backend:Linter crashed.
```

**Comment by kaste** [comment]
Oh, I see. This will be an easy fix. Thanks for reporting.

**Comment by kaste** [comment]
The PR is #14 

Please report if this works.

**Comment by kaste** [comment]
Good, then I merge and release
